import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Navbar/navbar";
import Skills from "./component/Skills/Skills";
import Work_Exprience from "./component/Work_Experience/Work_Exprience";
import Contact_me from "./component/Contact_me/Contact_me";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {/* <Skills /> */}

          <main
            className="relative overflow-hidden"
            style={{
              position: "relative",
              overflow: "hidden",
            }}
          >
            {children} <Contact_me />
          </main>
        </div>
      </body>
    </html>
  );
}
